exclude: ais/data/machine_annotations/tsr/standard_rendezvous.csv
exclude_types: ["*.geojson"]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args:
          [
            --install-types,
            --ignore-missing-imports,
            --disallow-untyped-defs,
            --ignore-missing-imports,
            --non-interactive,
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        exclude: ^tests/
        args:
          - -s
          - B101
  - repo: local
    hooks:
      - id: interrogate
        name: interrogate
        language: system
        entry: interrogate
        types: [python]
        args:
          [
            --ignore-init-method,
            --ignore-init-module,
            -p,
            -vv,
            ais,
            --fail-under=80,
          ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.257"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore, "E501"]
